### ISSUE TITLE
Sorry you know what permission I have to assign to allow me to send the commands from telegram as it returns me: Permission denied. Find your own tree!

### ISSUE THREAD

**Issue by byruggero** [Dih5/adminbot#1]

**Comment by Dih5** [comment]
That message is returned when a user who is not in the admin_list talks to the bot. As it is explained in the Running section of the readme, if you check the console where the bot is running you will see a log of the message with your user id, you have to add this id to the *.json file and restart the bot.

I'll update the message to something clearer tomorrow.

**Comment by Dih5** [comment]
Issue closed by 32dc639feee1d1606a08ffa6701999025eeb6624.

However, if you need further assistance to run the bot, do not hesitate to ask here.
